version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: demo
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    networks:
        - demo
volumes:
  mysql-data:

networks:
  demo: